v1 = input('Digite qualquer coisa: ')
print(v1.isnumeric())
print(v1.isalnum())
print(v1.isalpha())
print(v1.isascii())
print(v1.isdigit())
print(v1.isdecimal())
print(v1.isidentifier())
print(v1.islower())
print(v1.isprintable())
print(v1.isspace())
print(v1.istitle())
print(v1.isupper())